//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petbook_mvc_red0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adoption
    {
        public string owner_name { get; set; }
        public string owner_last { get; set; }
        public string user_email { get; set; }
        public string owned_pet { get; set; }
        public string reason { get; set; }
    }
}
