//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petbook_mvc_red0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Found
    {
        public string owner_name { get; set; }
        public string user_name { get; set; }
        public string user_contact { get; set; }
        public string date_found { get; set; }
        public string animaltype { get; set; }
        public string description { get; set; }
        public string location { get; set; }
    }
}
