//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace petbook_mvc_red0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lost
    {
        public string owner_name { get; set; }
        public string user_email { get; set; }
        public string user_contact { get; set; }
        public string country { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string gender { get; set; }
        public string pet { get; set; }
        public string identification { get; set; }
        public string pet_age { get; set; }
        public string pet_breedtype { get; set; }
        public string pet_colormarking { get; set; }
        public string message { get; set; }
        public string s_identification { get; set; }
    }
}
